/**
 * Study Group API
 * API for managing study groups
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface GroupCountByNameResponse
 */
export interface GroupCountByNameResponse {
  /**
   *
   * @type {string}
   * @memberof GroupCountByNameResponse
   */
  groupName?: string;
  /**
   *
   * @type {number}
   * @memberof GroupCountByNameResponse
   */
  count?: number;
}
