/**
 * Study Group API
 * API for managing study groups
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Person
 */
export interface Person {
  /**
   *
   * @type {string}
   * @memberof Person
   */
  name?: string;
  /**
   *
   * @type {Date}
   * @memberof Person
   */
  birthday?: Date;
  /**
   *
   * @type {number}
   * @memberof Person
   */
  height?: number;
  /**
   *
   * @type {number}
   * @memberof Person
   */
  weight?: number;
  /**
   *
   * @type {string}
   * @memberof Person
   */
  passportID?: string;
}
