/**
 * Study Group API
 * API for managing study groups
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StudyGroup } from "./StudyGroup";
import { StudyGroupsResponsePageable } from "./StudyGroupsResponsePageable";
import { StudyGroupsResponsePageableSort } from "./StudyGroupsResponsePageableSort";
/**
 *
 * @export
 * @interface StudyGroupsResponse
 */
export interface StudyGroupsResponse {
  /**
   *
   * @type {Array<StudyGroup>}
   * @memberof StudyGroupsResponse
   */
  content?: Array<StudyGroup>;
  /**
   *
   * @type {StudyGroupsResponsePageable}
   * @memberof StudyGroupsResponse
   */
  pageable?: StudyGroupsResponsePageable;
  /**
   *
   * @type {boolean}
   * @memberof StudyGroupsResponse
   */
  last?: boolean;
  /**
   *
   * @type {number}
   * @memberof StudyGroupsResponse
   */
  totalPages?: number;
  /**
   *
   * @type {number}
   * @memberof StudyGroupsResponse
   */
  totalElements?: number;
  /**
   *
   * @type {number}
   * @memberof StudyGroupsResponse
   */
  size?: number;
  /**
   *
   * @type {number}
   * @memberof StudyGroupsResponse
   */
  number?: number;
  /**
   *
   * @type {StudyGroupsResponsePageableSort}
   * @memberof StudyGroupsResponse
   */
  sort?: StudyGroupsResponsePageableSort;
  /**
   *
   * @type {boolean}
   * @memberof StudyGroupsResponse
   */
  first?: boolean;
  /**
   *
   * @type {number}
   * @memberof StudyGroupsResponse
   */
  numberOfElements?: number;
  /**
   *
   * @type {boolean}
   * @memberof StudyGroupsResponse
   */
  emmpty?: boolean;
}
