/**
 * Study Group API
 * API for managing study groups
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StudyGroupsResponsePageableSort } from "./StudyGroupsResponsePageableSort";
/**
 *
 * @export
 * @interface StudyGroupsResponsePageable
 */
export interface StudyGroupsResponsePageable {
  /**
   *
   * @type {number}
   * @memberof StudyGroupsResponsePageable
   */
  pageNumber?: number;
  /**
   *
   * @type {number}
   * @memberof StudyGroupsResponsePageable
   */
  pageSize?: number;
  /**
   *
   * @type {StudyGroupsResponsePageableSort}
   * @memberof StudyGroupsResponsePageable
   */
  sort?: StudyGroupsResponsePageableSort;
  /**
   *
   * @type {number}
   * @memberof StudyGroupsResponsePageable
   */
  offset?: number;
  /**
   *
   * @type {boolean}
   * @memberof StudyGroupsResponsePageable
   */
  paged?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof StudyGroupsResponsePageable
   */
  unpaged?: boolean;
}
