/**
 * Study Group API
 * API for managing study groups
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Person } from "./Person";
import {
  StudyGroupFormOfEducationEnum,
  StudyGroupSemesterEnum,
} from "./StudyGroup";
/**
 *
 * @export
 * @interface StudyGroupRequest
 */
export interface StudyGroupRequest {
  /**
   *
   * @type {string}
   * @memberof StudyGroupRequest
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof StudyGroupRequest
   */
  studentsCount?: number;
  /**
   *
   * @type {string}
   * @memberof StudyGroupRequest
   */
  formOfEducation?: StudyGroupFormOfEducationEnum;
  /**
   *
   * @type {string}
   * @memberof StudyGroupRequest
   */
  semesterEnum?: StudyGroupSemesterEnum;
  /**
   *
   * @type {Person}
   * @memberof StudyGroupRequest
   */
  groupAdmin?: Person;
}

/**
 * @export
 * @enum {string}
 */
export enum StudyGroupRequestFormOfEducationEnum {
  DISTANCEEDUCATION = "DISTANCE_EDUCATION",
  FULLTIMEEDUCATION = "FULL_TIME_EDUCATION",
  EVENINGCLASSES = "EVENING_CLASSES",
}
/**
 * @export
 * @enum {string}
 */
export enum StudyGroupRequestSemesterEnumEnum {
  THIRD = "THIRD",
  FIFTH = "FIFTH",
  SIXTH = "SIXTH",
}
