/**
 * Study Group API
 * API for managing study groups
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Person } from "./Person";

/**
 *
 * @export
 * @interface StudyGroup
 */
export interface StudyGroup {
  /**
   *
   * @type {number}
   * @memberof StudyGroup
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof StudyGroup
   */
  name?: string;

  /**
   *
   * @type {Date}
   * @memberof StudyGroup
   */
  creationDate?: Date;
  /**
   *
   * @type {number}
   * @memberof StudyGroup
   */
  studentsCount?: number;
  /**
   *
   * @type {string}
   * @memberof StudyGroup
   */
  formOfEducation?: StudyGroupFormOfEducationEnum;
  /**
   *
   * @type {string}
   * @memberof StudyGroup
   */
  semesterEnum?: StudyGroupSemesterEnumEnum;
  /**
   *
   * @type {Person}
   * @memberof StudyGroup
   */
  groupAdmin?: Person;
}

/**
 * @export
 * @enum {string}
 */
export enum StudyGroupFormOfEducationEnum {
  DISTANCEEDUCATION = "DISTANCE_EDUCATION",
  FULLTIMEEDUCATION = "FULL_TIME_EDUCATION",
  EVENINGCLASSES = "EVENING_CLASSES",
}

/**
 * @export
 * @enum {string}
 */
export enum StudyGroupSemesterEnumEnum {
  THIRD = "THIRD",
  FIFTH = "FIFTH",
  SIXTH = "SIXTH",
}
