server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: 12345678
    key-alias: tomcat
    key-password: 12345678

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ya-pidor
          uri: lb://STUDY-GROUP-SERVICE
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
        - id: dima-pidor
          uri: lb://ISU-SERVICE
          predicates:
            - Path=/api/v1/isu/**
          filters:
            - StripPrefix=3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka