server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:seerver.jks
    key-store-password: iveriver
    key-store-type: jks
    key-alias: iver
    key-password: iveriver

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ya-pidor
          uri: lb://STUDY-GROUP-SERVICE
          order: 2
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
        - id: dima-pidor
          uri: lb://ISU-SERVICE
          order: 1
          predicates:
            - Path=/api/v1/isu/**
          filters:
            - StripPrefix=3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka