server:
  port: 0

spring:
  application:
    name: STUDY-GROUP-SERVICE
  profiles:
    active: development
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: admin